### ISSUE TITLE
Move NDI elements into gstreamer/gst-plugins-rs

### ISSUE THREAD

**Issue by rubenrua** [teltek/gst-plugin-ndi#35]
@sdroege, What is your opinion about moving NDI elements into [gstreamer/gst-plugins-rs](https://github.com/sdroege/gst-plugin-rs)?

PD: Thank you for your work in this repo.

**Comment by sdroege** [comment]
I'm not sure about this. It requires a proprietary SDK and we can't build it automatically as part of the CI because of that (the OBS Debian packages IMHO violate the license of the SDK).

If you don't intend to continue maintaining the crate, I'd be fine to take it over though and will think about where to put it best and how.

That said, I'm planning more work on it in the next days regardless of this.

**Comment by rubenrua** [comment]
We intend to continue maintaining the crate. The purpose of using 'gst-plugins-rs' is facilitated a future distribution.

**Comment by sdroege** [comment]
In that case I see no point in having the plugin in gst-plugins-rs. Having it maintained in two different places is only going to cause confusion to users :)

**Comment by sdroege** [comment]
So what should we do here? Just close?

**Comment by sdroege** [comment]
This was actually done now: https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs/-/tree/main/net/ndi
